### ISSUE TITLE
Example IAM policy

### ISSUE THREAD

**Issue by jdoss** [KennaSecurity/Kenna-Action#1]
I see this needs an IAM user with keys to access AWS Inspector. What are the minimal permissions required for this to run on AWS and can we get some documentation on an example IAM policy?

**Comment by jgamblin** [comment]
Hi @jdoss,

AWS has a [AmazonInspectorReadOnlyAccess](https://docs.aws.amazon.com/inspector/latest/userguide/security_iam_id-based-policy-examples.html) policy that would be my suggestion for use but as always minimum rights should be applied.
