### ISSUE TITLE
Use container from quay.io/repository/kennasecurity/toolkit 

### ISSUE THREAD

**Issue by jdoss** [KennaSecurity/Kenna-Action#2]
Instead of checking out the code and doing a bunch of work in the action, you can use https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer to pull down the https://quay.io/repository/kennasecurity/toolkit?tag=latest&tab=tags container and just run `bundle exec ruby toolkit.rb  task=aws_inspector ...` that way.

**Comment by jgamblin** [comment]
Thanks,  I will work with @ebellis on a plan forward.
